Remove django-storages ACL config
I'm seeing this error in my ECS application when collectstatic runs:

> botocore.exceptions.ClientError: An error occurred (AccessControlListNotSupported)
> when calling the PutObject operation: The bucket does not allow ACLs

It seems that ACLs are deprecated and the current way to do this in AWS
is via a bucket policy or using cloudfront.